---
- hosts: L016215

  tasks:
  - name: join domain
    win_domain_membership:
      dns_domain_name: "{{ domain }}"
      domain_admin_user: "{{ domains[domain]['domain_admin_user'] }}"
      domain_admin_pasword: "{{ lookup('identityserver', tag=domains[domain]['tag'], type='administrator', login=domains[domain]['domain_admin_user'], domain=domain, is_internal=True) }}"
      state: domain
      domain_ou_path: "{{ domains[domain]['domain_ou_path'] }}"
    register: domain_state

  - name: reboot if necessary after changing domain membership
    win_reboot:
    when: domain_state.reboot_required

  vars:
    domains:
      staging.local:
        domain_admin_user: Administrator
        domain_ou_path: "OU=Servers,DC=staging,DC=local"
        tag: L016215
